/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./views/**/*.templ", "./views/**/*.go"],
  theme: {
    fontFamily: {
      cascadia: ['"Cascadia Code"', "monospace"],
      lato: ["Lato", "sans-serif"],
      sourcesans: ['"Source Sans 3"', "sans-serif"],
    },
  },
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
    darkTheme: "night",
  },
  darkMode: ["class", '[data-theme="night"]'],
};
