name: Deploy chipa.me

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"

            - name: Build
              run: go build -v -o chipa-me ./cmd

            - name: Test
              run: go test -v ./...

            - name: List directory contents
              run: ls -la

            - name: Set up SSH key
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
                  chmod 600 ~/.ssh/deploy_key
                  ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: Deploy to server
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
              run: |
                  # Stop the service before deployment
                  ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
                  sudo systemctl stop chipa-me.service || true
                  '

                  # Create directory structure on the server
                  ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'mkdir -p ~/chipa-me/bin ~/chipa-me/static ~/chipa-me/posts'

                  # Copy binary, static files, and posts
                  scp -i ~/.ssh/deploy_key ./chipa-me ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/chipa-me/bin/
                  scp -i ~/.ssh/deploy_key -r ./static/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/chipa-me/static/
                  # scp -i ~/.ssh/deploy_key -r ./posts/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/chipa-me/posts/

                  # Create systemd service file
                  echo "[Unit]
                  Description=chipa.me Web Server
                  After=network.target
                  Wants=network-online.target

                  [Service]
                  Restart=always
                  Type=simple
                  ExecStart=/root/chipa-me/bin/chipa-me
                  WorkingDirectory=/root/chipa-me
                  User=root

                  [Install]
                  WantedBy=multi-user.target" | ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'cat > /etc/systemd/system/chipa-me.service'

                  # Reload systemd, enable and restart the service
                  ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
                  sudo systemctl daemon-reload
                  sudo systemctl enable chipa-me.service
                  sudo systemctl start chipa-me.service
                  '

            - name: Verify deployment
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
              run: |
                  ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
                    systemctl is-active --quiet chipa-me.service && echo "Service is running" || echo "Service failed to start"
                  '
